_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: daemon-sets.yaml
backups: false
helm: false
ingress: false
labels: 'app.kubernetes.io/name: kube-vip'
name: kube-vip
namespace: kube-vip
pvc: false
reloader: false
resources:
- rbac.yaml
- service-accounts.yaml
service: false
serviceAccount: false
upstreamURL: https://kube-vip.io
url: https://github.com/charlesthomas/homelab-kube-vip
