---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-vip

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-kube-vip
commonLabels:
  app.kubernetes.io/name: kube-vip

resources:
- resources/daemon-sets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
