---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-vip

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-kube-vip
commonLabels:
  app.kubernetes.io/name: kube-vip

resources:
- resources/daemon-sets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: kube-vip
      namespace: kube-vip
      annotations:
        gethomepage.dev/href: https://kube-vip.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: kube-vip
        gethomepage.dev/name: kube-vip
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
